dist: trusty
language: cpp
matrix:
  include:
    - os: osx
      before_install:
        - brew update
      script:
        - brew install https://survex.com/~olly/survex.rb
        - brew test https://survex.com/~olly/survex.rb
branches:
  only:
    - travis-osx
