dist: trusty
language: cpp
matrix:
  include:
    - os: osx
      before_install:
        - brew update
      script:
        - brew tap survex/homebrew-survex https://git.survex.com/homebrew-survex
        - brew install survex/homebrew-survex/survex
        - brew test survex/homebrew-survex/survex
branches:
  only:
    - travis-osx
